CodingTestApp/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CodingTestApp.Models
{
    public class Contact
    {
        public Contact()
        {

        }
        public int ID { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Email { get; set; }
        public String Address { get; set; }
        public Double? Longitude { get; set; }
        public Double? Latitude { get; set; }
    }
}

CodingTestApp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CodingTestApp.Models;
using CodingTestApp.DataContext;

namespace CodingTestApp.Controllers
{
    public class ContactController : Controller
    {
        private ContactContext db = new ContactContext();


        // GET: /Contact/

        //public ActionResult Index()
        //{
        //    return View(db.Contacts.ToList());
        //}

        public ActionResult Index(String Field = "", String Value = "")
        {
            if (Field == "" || Value == "")
            {
                return View(db.Contacts.ToList());
            }
            else
            {
                IQueryable<Contact> contacts = db.Contacts;
                switch (Field)
                {
                    case "First":
                        contacts = from c in db.Contacts
                                   where c.FirstName.Contains(Value)
                                   select c;
                        break;
                    case "Last":
                        contacts = from c in db.Contacts
                                   where c.LastName.Contains(Value)
                                   select c;
                        break;
                    case "Email":
                        contacts = from c in db.Contacts
                                   where c.Email.Contains(Value)
                                   select c;
                        break;
                    case "Address":
                        contacts = getContactsByDistance(contacts.ToList(), Value);
                            break;
                    default:
                        break;
                }
                return View(contacts.ToList());
            }
        }

        private IQueryable<Contact> getContactsByDistance(List<Contact> contacts, String coords)
        {
            String[] words = coords.Split(',');
            double latitude = Convert.ToDouble(words[0]);
            double longitude = Convert.ToDouble(words[1]);
            List<Contact> list = new List<Contact>();
            double minDist = -1;

            //Contact[] minDistList = new Contact[contacts.ToArray().Length];

            for (var i = 0; i < contacts.Count; i++)
            {
                if (!String.IsNullOrEmpty(contacts[i].Address))
                {
                    var dist = Math.Abs((contacts[i].Longitude.Value - longitude))
                        + Math.Abs(contacts[i].Latitude.Value - latitude);

                    if (minDist == -1)
                    {
                        minDist = dist;
                        list.Add(contacts[i]);
                    }
                    else if (dist < minDist)
                    {
                        list.Clear();
                        list.Add(contacts[i]);
                        minDist = dist;
                    }
                    else if (dist == minDist)
                    {
                        list.Add(contacts[i]);
                    }
                }
            }

            return list.AsQueryable();
        }


        // GET: /Contact/Details/5

        public ActionResult Details(int id = 0)
        {
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        //
        // GET: /Contact/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Contact/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        //
        // GET: /Contact/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        //
        // POST: /Contact/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contact contact)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contact);
        }

        //
        // GET: /Contact/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        //
        // POST: /Contact/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = db.Contacts.Find(id);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CodingTestApp/Views/Contact/Create.cshtml
@model CodingTestApp.Models.Contact

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Contact</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-field">
            @Html.HiddenFor(model => model.Longitude)
        </div>

        <div class="editor-field">
            @Html.HiddenFor(model => model.Latitude)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("form").submit(function (event) {
            var text = $('#Address').val();
            var addressString = text.trim().split(' ').join('+')
            if (text.length) {
                $.ajax({
                    url: "https://maps.googleapis.com/maps/api/geocode/json?address=" + addressString + "&sensor=false",
                    async: false,
                    success: function (data) {
                        var result = data.results[0];
                        var translatedAddress = result.formatted_address;
                        $('#Longitude').val(result.geometry.location.lng);
                        $('#Latitude').val(result.geometry.location.lat);
                        $('#Address').val(translatedAddress);
                    }
                });
            }
        });
    </script>
}

CodingTestApp/Views/Contact/Delete.cshtml
@model CodingTestApp.Models.Contact

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Contact</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Longitude)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Longitude)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Latitude)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Latitude)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CodingTestApp/Views/Contact/Details.cshtml
@model CodingTestApp.Models.Contact

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Contact</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Longitude)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Longitude)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Latitude)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Latitude)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CodingTestApp/Views/Contact/Edit.cshtml
@model CodingTestApp.Models.Contact

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Contact</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Longitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Longitude)
            @Html.ValidationMessageFor(model => model.Longitude)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Latitude)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Latitude)
            @Html.ValidationMessageFor(model => model.Latitude)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CodingTestApp/Views/Contact/Index.cshtml
@model IEnumerable<CodingTestApp.Models.Contact>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("Index", "Contact", FormMethod.Get))
{
     <select name="Field" id="Field">
        <option value="First">First</option>
        <option value="Last">Last</option>
        <option value="Email">Email</option>
        <option value="Address">Address</option>
    </select>
    <input type="text" name="Value" id="Value" />
    <input type="button" id="btnSubmit" value="Filter" />   
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Latitude)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#Field").change(function () {
            if ($("#Field option:selected").val() == "Address") {
                $("#Value").hide();
                $("#btnSubmit").val("Get Closest Contact");
            } else {
                $("#Value").show();
                $("#btnSubmit").val("Filter");
            }
        });

        $("#btnSubmit").click(function (event) {
            if ($("#Field").val() != "Address") {
                $("form").submit();
            }
            else if (navigator.geolocation) {
                var timeoutVal = 10 * 1000 * 1000;
                navigator.geolocation.getCurrentPosition(
                  displayPosition,
                  displayError,
                  { enableHighAccuracy: true, timeout: timeoutVal, maximumAge: 0 }
                );
            }
            else {
                alert("Geolocation is not supported by this browser");
            }

            function displayError(error) {
                var errors = {
                    1: 'Permission denied',
                    2: 'Position unavailable',
                    3: 'Request timeout'
                };
                alert("Error: " + errors[error.code]);
            }

            function displayPosition(position) {
                $("#Value").val(position.coords.latitude + ',' + position.coords.longitude);
                $("form").submit();
            }
        });
    </script>
}

CodingTestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>